#Test
print("Nест по антропологии")
print("Напишите какая первая стадия развития человека,")
print("Первая стадия:", input())
print("Напишите какая вторая стадия развития человека,")
print("Вторая стадия:", input())
print("Напишите какая третья стадия развития человека,")
print("Третья стадия:", input())
print("Напишите какая четвертая стадия развития человека,")
print("Четвертая стадия:", input())
print("Ответы")
print("1 стадия:","Australopithecus", sep="=>")
print("2 стадия:","Homo erectus", sep="=>")
print("3 стадия:","Homo primigenius", sep="=>")
print("4 стадия:","Homo sapiens sapiens", sep="=>")